added home page cards, and edited footer
Entertainment1080/pagelender pull request #5
Opened 2020-11-05 19:22 UTC by Drewbrad4

Added our home page links and a scroll function and a link to the footer.

2020-11-05 19:36 UTC, talk2MeGooseman commented on app/javascript/components/Pages/BorrowShow.js
> -BorrowShow.propTypes = {
NICE!

2020-11-05 19:36 UTC, talk2MeGooseman commented on app/javascript/components/Pages/BorrowedShow.js
> -BorrowedShow.propTypes = {
NICE!

2020-11-05 19:39 UTC, talk2MeGooseman requested changes

2020-11-05 19:39 UTC, talk2MeGooseman commented on app/javascript/components/Pages/Home.js
> +                <br></br>
Instead of br tags, you can also try creating css styles to do padding on the bottom.

2020-11-06 01:26 UTC, devJoelMichael commented
Looks good

2020-11-06 01:35 UTC, devJoelMichael approved these changes

2020-11-06 01:39 UTC, merged